# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logged.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtGui import *
from PyQt5.QtCore import *


class Ui_Dialog(object):
    def setupUi(self, Dlg):
        Dlg.setObjectName("Dlg")
        Dlg.resize(800, 700)
        Dlg.setStyleSheet("background-image:url(icon/bgg.jpg)")
        self.pushButton1 = QtWidgets.QPushButton(Dlg)
        self.pushButton1.setGeometry(QtCore.QRect(200, 40, 350, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(15)
        self.layout = QGridLayout(Dlg)
        self.pushButton1.setFont(font)
        self.pushButton1.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(255, 0, 0);")
        self.pushButton1.setAutoFillBackground(True)
        self.pushButton1.setObjectName("pushbutton1")
        self.layout.addWidget(self.pushButton1,0,2)
        self.label_2 = QtWidgets.QLabel(Dlg)
        self.layout.addWidget(self.label_2, 2, 1)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-image:url(icon/white.jpg);\n"
"color: rgb(0, 0, 0);")
        self.label_3 = QtWidgets.QLabel(Dlg)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 61, 21))
        self.layout.addWidget(self.label_3, 3, 1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-image:url(icon/white.jpg);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(Dlg)
        self.layout.addWidget(self.label_4, 5, 1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-image:url(icon/white.jpg);\n"
                                   "color: rgb(0, 0, 0);\n"
                                   "")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dlg)
        self.layout.addWidget(self.label_5, 6, 1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-image:url(icon/white.jpg);\n"
                                   "color: rgb(0, 0, 0);\n"
                                   "")
        self.label_6 = QtWidgets.QLabel(Dlg)
        self.layout.addWidget(self.label_6, 6, 4)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-image:url(icon/white.jpg);\n"
                                   "color: rgb(0, 0, 0);\n"
                                   "")
        self.pushButton = QtWidgets.QPushButton(Dlg)
        self.pushButton.setGeometry(QtCore.QRect(220, 260, 75, 23))
        self.pushButton.setStyleSheet("color: yellow;")
        self.pushButton.setObjectName("pushButton")
        # self.pushButton.clicked.connect(self.reg)
        self.layout.addWidget(self.pushButton, 7, 1)

        self.pushButton2 = QtWidgets.QPushButton(Dlg)
        self.pushButton2.setGeometry(QtCore.QRect(220, 260, 75, 23))
        self.pushButton2.setStyleSheet("color: yellow;")
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton2.setMinimumSize(10, 10)
        self.pushButton2.setMaximumSize(140, 40)
        self.pushButton2.clicked.connect(self.hey)
        self.layout.addWidget(self.pushButton2, 7, 2)
        self.lineEdit = QtWidgets.QLineEdit(Dlg)
        self.lineEdit.setGeometry(QtCore.QRect(100, 100, 261, 20))
        self.lineEdit.setStyleSheet("background-image:url(icon/white.jpg);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.layout.addWidget(self.lineEdit, 2, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dlg)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setStyleSheet("background-image:url(icon/white.jpg);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.layout.addWidget(self.lineEdit_2, 3, 2)

        self.lineEdit_3 = QtWidgets.QLineEdit(Dlg)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 170, 261, 20))
        self.lineEdit_3.setStyleSheet("background-image:url(icon/white.jpg);\n"
"color: rgb(0, 0, 0);")
        self.layout.addWidget(self.lineEdit_3, 5, 2)
        self.comboBox = QComboBox(Dlg)
        self.comboBox.addItem("Male")
        self.comboBox.addItem("Female")
        self.comboBox.addItem("Other")
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "color: rgb(0, 0, 0);")
        self.layout.addWidget(self.comboBox, 6, 2)
        self.lineEdit_4 = QtWidgets.QLineEdit(Dlg)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 170, 261, 20))
        self.lineEdit_4.setStyleSheet("background-image:url(icon/white.jpg);\n"
                                      "color: rgb(0, 0, 0);")
        self.layout.addWidget(self.lineEdit_4, 6, 5)
        self.retranslateUi(Dlg)
        QtCore.QMetaObject.connectSlotsByName(Dlg)
        # self.b = False
        # self.pushButton3.clicked.connect(Dlg.close)

    def retranslateUi(self, Dlg):
        _translate = QtCore.QCoreApplication.translate
        Dlg.setWindowTitle(_translate("Dlg", "Profile"))
        self.pushButton1.setText(_translate("Dlg", "  User Profile "))
        self.label_2.setText(_translate("Dlg", " Email Id"))
        self.label_3.setText(_translate("Dlg", " Set Password  "))
        self.label_4.setText(_translate("Dlg", " Name  "))
        self.label_5.setText(_translate("Dlg", " Gender  "))
        self.label_6.setText(_translate("Dlg", " Mobile No.  "))
        self.pushButton.setText(_translate("Dlg", "Register"))
        self.pushButton2.setText(_translate("Dlg", "Log In"))
        self.lineEdit.setPlaceholderText(_translate("Dlg"," Email "))
        self.lineEdit_2.setPlaceholderText(_translate("Dlg"," Password"))
        self.lineEdit_3.setPlaceholderText(_translate("Dlg"," Name "))
        self.lineEdit_4.setPlaceholderText(_translate("Dlg", " Mobile "))


    def hey(self):
        dlg = QtWidgets.QDialog()
        dlg.setObjectName("dlg")
        dlg.resize(800, 700)
        dlg.setStyleSheet("background-image:url(icon/bgg.jpg)")
        dlg.setWindowTitle("Log In")
        layout = QGridLayout(dlg)
        label4 = QtWidgets.QLabel(dlg)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        label4.setFont(font)
        label4.setStyleSheet("background-image:url(icon/white.jpg);\n"
                                   "color: rgb(0, 0, 0);\n")
        label4.setText(" E-mail Id ")
        layout.addWidget(label4, 3, 0)
        lineEdit1 = QtWidgets.QLineEdit(dlg)
        lineEdit1.setStyleSheet("background-image:url(icon/white.jpg);\n"
                                    "color: rgb(0, 0, 0);")
        lineEdit1.setEnabled(True)
        layout.addWidget(lineEdit1, 3, 1)
        lineEdit1.setPlaceholderText(" Email ")

        font1 = QtGui.QFont()
        font1.setFamily("Segoe UI Black")
        font1.setPointSize(20)
        font1.setBold(True)
        pushButton1 = QtWidgets.QPushButton(dlg)
        pushButton1.setFont(font1)
        pushButton1.setMaximumSize(250,70)
        pushButton1.setStyleSheet("color: red;")
        pushButton1.setObjectName("pushButton1")
        pushButton1.setText("Log In" )
        # pushButton1.clicked.connect(self.prof)
        layout.addWidget(pushButton1, 0, 1)
        lineEdit2 = QtWidgets.QLineEdit()
        lineEdit2.setEnabled(True)
        lineEdit2.setGeometry(QtCore.QRect(160, 170, 261, 20))
        lineEdit2.setStyleSheet("background-image:url(icon/white.jpg);\n"
                                      "color: rgb(0, 0, 0);")
        layout.addWidget(lineEdit2, 4, 1)
        lineEdit2.setPlaceholderText(" Password")
        label5 = QtWidgets.QLabel(dlg)
        label5.setFont(font)
        label5.setStyleSheet("background-image:url(icon/white.jpg);\n"
                             "color: rgb(0, 0, 0);\n"
                             "")
        label5.setText(" Password ")
        layout.addWidget(label5, 4, 0)
        pushButton2 = QtWidgets.QPushButton(dlg)
        pushButton2.setGeometry(QtCore.QRect(220, 260, 75, 23))
        pushButton2.setStyleSheet("color: yellow;")
        pushButton2.setObjectName("pushButton2")
        layout.addWidget(pushButton2, 5, 0)
        pushButton2.setText("Register")
        pushButton2.clicked.connect(self.clicked)
        pushButton2.clicked.connect(dlg.close)

        self.pushButton3 = QtWidgets.QPushButton(dlg)
        self.pushButton3.setGeometry(QtCore.QRect(220, 260, 75, 23))
        self.pushButton3.setStyleSheet("color: yellow;")
        self.pushButton3.setObjectName("pushButton3")
        # pushButton2.clicked.connect(self.hey)
        layout.addWidget(self.pushButton3, 5, 1)
        self.pushButton3.setMinimumSize(10,10)
        self.pushButton3.setMaximumSize(140, 40)
        self.pushButton3.setText("Log In")
        self.pushButton3.clicked.connect(dlg.close)
        # self.pushButton3.clicked.connect(self.prof.Dlg)

        # self.pushButton3.clicked.connect(dlg.close)
        dlg.exec_()

    def clicked(self):
        pass

    def prof(self,Dlg):
        pass

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dlg = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dlg)
#     Dlg.show()
#     # Dlg.exec_()
#     sys.exit(app.exec_())
